#!/bin/bash
device=$1
node=$2
value=0
while :
do
    echo "Sending value $value to device-$device from node $node"
    curl -H "Content-type: application/json" -X POST -d '{"entityId": "device-'$device'", "value": "'$value'"}' http://127.0.0.1:955$node/send-value
    echo
    value=$((value+1))
    sleep .5
done